### ISSUE TITLE
Does not compile on golang 1.9

### ISSUE THREAD

**Issue by AdrianLC** [go-fingerprint/fingerprint#1]
```
# github.com/go-fingerprint/gochroma/chromaprint
/go/src/github.com/go-fingerprint/gochroma/chromaprint/chromaprint.go:95: cannot use unsafe.Pointer(&data[0]) (type unsafe.Pointer) as type *C.int16_t in argument to func literal
/go/src/github.com/go-fingerprint/gochroma/chromaprint/chromaprint.go:130: cannot use ptr (type *unsafe.Pointer) as type **C.uint32_t in argument to func literal
```

It seems they have made the type checking more restrictive? I'm trying to fix it on my fork but honestly I'm just starting out with go and this is not exactly entry-level :joy:

**Comment by utkinis** [comment]
@AdrianLC btw consider using an automatic bindings generator: https://github.com/xlab/c-for-go, it is actively developed and easy to set up.

**Comment by noodlecak-e** [comment]
Can you walk me through this solution?
