### ISSUE TITLE
seems to be not  work very well 

### ISSUE THREAD

**Issue by ItsFunny** [go-fingerprint/fingerprint#2]
i choosed 2 songs   as the test case
- Charlie Puth,Selena Gomez - We Don't Talk Anymore.mp3
- Nisw,双笙,囧菌 - 【3D】We Don't Talk Anymore.mp3
and the result is 0.85 

then  i decide to test another 2 totally different songs but the result is still 0.85

**Comment by utkinis** [comment]
@ItsFunny `chromaprint` library expects raw input data, i.e. not encoded as mp3 or with any other codec. Refer to the documentation of libchromaprint (https://github.com/acoustid/chromaprint/blob/master/src/chromaprint.h). `fingerprint` and `gochroma` are nothing but a simple (and outdated) wrapper to `chromaprint`, if you want something more flexible and modern, consider https://github.com/xlab/c-for-go, it allows you to generate Go bindings to any C library

**Comment by ItsFunny** [comment]
thx very much ,really appreciate it
